# Generated by Django 4.1.2 on 2022-11-25 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lacrosse_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='injury',
            name='date',
            field=models.DateField(),
        ),
    ]
