# Generated by Django 4.1.2 on 2022-12-19 07:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lacrosse_app', '0002_alter_injury_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depth', models.CharField(choices=[('out', 'アウト'), ('just', 'ぴったり')], max_length=4)),
                ('string', models.BooleanField(default=True)),
                ('end', models.BooleanField(default=True)),
                ('ball', models.CharField(choices=[('out', '落ちない'), ('safe', '落ちづらい')], max_length=5)),
                ('length', models.FloatField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)])),
                ('narrow', models.FloatField(validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(9)])),
                ('height', models.FloatField(validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(9)])),
            ],
        ),
    ]
