# Generated by Django 4.1.2 on 2022-12-27 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lacrosse_app', '0003_stick'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stick',
            name='ball',
            field=models.IntegerField(choices=[(0, '落ちない'), (1, '落ちづらい')], null=True),
        ),
        migrations.AlterField(
            model_name='stick',
            name='depth',
            field=models.IntegerField(choices=[(0, 'アウト'), (1, 'ぴったり')], null=True),
        ),
        migrations.AlterField(
            model_name='stick',
            name='end',
            field=models.IntegerField(choices=[(0, 'アウト')], null=True),
        ),
        migrations.AlterField(
            model_name='stick',
            name='string',
            field=models.IntegerField(choices=[(0, 'アウト')], null=True),
        ),
    ]
