# Generated by Django 4.1.2 on 2022-12-27 07:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lacrosse_app', '0004_alter_stick_ball_alter_stick_depth_alter_stick_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stick',
            name='height',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(9)]),
        ),
        migrations.AlterField(
            model_name='stick',
            name='length',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)]),
        ),
        migrations.AlterField(
            model_name='stick',
            name='narrow',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(9)]),
        ),
    ]
