# Generated by Django 4.1.2 on 2023-01-10 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lacrosse_app', '0005_alter_stick_height_alter_stick_length_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stick',
            name='player',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sticks', to='lacrosse_app.player'),
            preserve_default=False,
        ),
    ]
