# Generated by Django 4.1.2 on 2023-01-17 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lacrosse_app', '0007_shot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shot',
            name='times',
            field=models.IntegerField(),
        ),
    ]
