# Generated by Django 4.1.2 on 2023-01-17 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lacrosse_app', '0008_alter_shot_times'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shot',
            old_name='times',
            new_name='count',
        ),
    ]
