# Generated by Django 4.1.2 on 2023-01-22 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lacrosse_app', '0009_rename_times_shot_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shot',
            name='count',
        ),
        migrations.AddField(
            model_name='shot',
            name='bd',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shot',
            name='gb',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shot',
            name='pc',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shot',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shot',
            name='shot_all',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shot',
            name='shot_goal',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shot',
            name='shot_in',
            field=models.IntegerField(default=0),
        ),
    ]
