# Generated by Django 4.1.2 on 2023-01-29 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lacrosse_app', '0010_remove_shot_count_shot_bd_shot_gb_shot_pc_shot_score_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('image', models.ImageField(upload_to='images')),
                ('content', models.TextField(verbose_name='content')),
                ('date', models.TextField(verbose_name='date')),
            ],
        ),
    ]
